version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  game_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/game.log
    maxBytes: 10485760
    backupCount: 20

  procedural_gen_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/procedural_gen.log
    maxBytes: 10485760
    backupCount: 20

loggers:
  game:
    level: DEBUG
    handlers: [console, game_file]
    propagate: no

  procedural_gen:
    level: DEBUG
    handlers: [console, procedural_gen_file]
    propagate: no

