version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  console_message:
    format: '%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console_message
    stream: ext://sys.stdout

  game_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/game.log
    maxBytes: 10485760
    backupCount: 20

  procedural_gen_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/procedural_gen.log
    maxBytes: 10485760
    backupCount: 20
  
  benchmark_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/benchmark.log
    maxBytes: 10485760
    backupCount: 20

  actions_log_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/actions.log
    maxBytes: 10485760
    backupCount: 20

  master_log_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/master.log
    maxBytes: 10485760
    backupCount: 20
  

loggers:
  game:
    level: DEBUG
    handlers: [console, game_file, master_log_file]
    propagate: no

  procedural_gen:
    level: DEBUG
    handlers: [console, procedural_gen_file, master_log_file]
    propagate: no

  benchmark:
    level: DEBUG
    handlers: [console, benchmark_file, master_log_file]
    propagate: no

  actions: 
    level: DEBUG
    handlers: [console, actions_log_file, master_log_file]
    propagate: no
